// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

[Table("EntradaEstoque")]
public partial class EntradaEstoque
{
    [Key]
    public int Id { get; set; }

    public int? NumeroNotaFiscal { get; set; }

    public int? FornecedorId { get; set; }

    public int? ProdutoId { get; set; }

    public int? QuantidadeEntrada { get; set; }

    [StringLength(50)]
    public string DepositoArmazenamento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [ForeignKey("FornecedorId")]
    [InverseProperty("EntradaEstoques")]
    public virtual Fornecedores Fornecedor { get; set; }

    [ForeignKey("ProdutoId")]
    [InverseProperty("EntradaEstoques")]
    public virtual Produto Produto { get; set; }
}