// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

public partial class Fornecedores
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    
    public string Nome { get; set; }

    [StringLength(255)]
    
    public string Endereço { get; set; }

    [StringLength(100)]
    
    public string Email { get; set; }

    [Column("CNPJ")]
    [StringLength(14)]
    
    public string Cnpj { get; set; }

    public int? InscricaoEstadual { get; set; }

    public int? InscricaoMunicipal { get; set; }

    [InverseProperty("Fornecedor")]
    public virtual ICollection<EntradaEstoque> EntradaEstoques { get; set; } = new List<EntradaEstoque>();

    [InverseProperty("Fornecedor")]
    public virtual ICollection<OrdemCompra> OrdemCompras { get; set; } = new List<OrdemCompra>();

    [InverseProperty("Fornecedor")]
    public virtual ICollection<Servicos> Servicos { get; set; } = new List<Servicos>();
}