// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

[Table("OrdemCompra")]
public partial class OrdemCompra
{
    [Key]
    public int Id { get; set; }

    public int? FornecedorId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCompra { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? PrecoPago { get; set; }

    [StringLength(100)]
    
    public string UsuarioCriacao { get; set; }

    [StringLength(100)]
    
    public string UsuarioPedidoInterno { get; set; }

    [StringLength(50)]
    
    public string TipoPedido { get; set; }

    [StringLength(100)]
    
    public string NomeProduto { get; set; }

    [StringLength(100)]
    
    public string NomeServico { get; set; }

    [ForeignKey("FornecedorId")]
    [InverseProperty("OrdemCompras")]
    public virtual Fornecedores Fornecedor { get; set; }
}