// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

public partial class Produto
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    
    public string Nome { get; set; }

    
    public string Descricao { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? ValorCompra { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? ValorVenda { get; set; }

    public int Ean {  get; set; }

    public int? QtdAtual { get; set; }

    public int? QtdMinima { get; set; }

    public byte[] Imagem { get; set; }

    [StringLength(20)]
    
    public string UnidadeDeMedida { get; set; }

    [InverseProperty("Produto")]
    public virtual ICollection<EntradaEstoque> EntradaEstoques { get; set; } = new List<EntradaEstoque>();

    [InverseProperty("Produto")]
    public virtual ICollection<SaidaEstoque> SaidaEstoques { get; set; } = new List<SaidaEstoque>();
}