// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

[Table("SaidaEstoque")]
public partial class SaidaEstoque
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    
    public string Usuario { get; set; }

    [StringLength(100)]
    
    public string DepartamentoSolicitante { get; set; }

    public int? ProdutoId { get; set; }

    public int? QuantidadeRetirada { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataCadastro { get; set; }

    [ForeignKey("ProdutoId")]
    [InverseProperty("SaidaEstoques")]
    public virtual Produto Produto { get; set; }
}