// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

public partial class Servicos
{
    [Key]
    public int Id { get; set; }

    [StringLength(100)]
    public string NomeServico { get; set; }

    public int? FornecedorId { get; set; }

    public string DescricaoServico { get; set; }

    public int? PrazoEntregaPadrao { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataAbertura { get; set; }

    [ForeignKey("FornecedorId")]
    [InverseProperty("Servicos")]
    public virtual Fornecedores Fornecedor { get; set; }
}